# Generated by Django 4.2.3 on 2023-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nom_participante', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], max_length=20)),
                ('hora_inscripcion', models.TimeField()),
                ('observacion', models.TextField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituciones')),
            ],
        ),
    ]
