# Generated by Django 4.2.3 on 2023-12-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
